name: static_json_serializable_annotation
description: A package exposing annotations for static_json_serializable_generator.
version: 0.1.0
homepage: https://github.com/ValentinVignal/flutter_packages/tree/main/packages/static_json_serializable/static_json_serializable_annotation
repository: https://github.com/ValentinVignal/flutter_packages
issue_tracker: https://github.com/ValentinVignal/flutter_packages/issues

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
