# cspell:ignore carryforward

comment:
  layout: "reach, diff, flags, files"

flags:
  animated_collection:
    paths:
      - packages/animated_collection/
    carryforward: true
  imperative_page_routes:
    paths:
      - packages/imperative_page_routes/
    carryforward: true
  riverpod_state_provider_generator:
    paths:
      - packages/riverpod_state_provider/riverpod_state_provider_generator/
    carryforward: true
  static_json_serializable_generator:
    paths:
      - packages/static_json_serializable/static_json_serializable_generator/
    carryforward: true

coverage:
  status:
    project:
      animated_collection: 
        flags:
          - animated_collection
      imperative_page_routes:
        flags:
          - imperative_page_routes
      riverpod_state_provider_generator:
        flags:
          - riverpod_state_provider_generator
      static_json_serializable_generator:
        flags:
          - static_json_serializable_generator
      
