# cspell:ignore carryforward

comment:
  layout: "reach, diff, flags, files"

flags:
  animated_collection:
    paths:
      - packages/animated_collection/
    carryforward: true
  imperative_page_routes:
    paths:
      - packages/imperative_page_routes/
    carryforward: true

coverage:
  status:
    project:
      animated_collection: 
        flags:
          - animated_collection
      imperative_page_routes:
        flags:
          - imperative_page_routes
