comment:
  layout: "reach, diff, flags, files"

flags:
  animated_collection:
    paths:
      - packages/animated_collection/

coverage:
  status:
    project:
      animated_collection: 
        flags:
          - animated_collection
