# cspell:ignore carryforward

comment:
  layout: "reach, diff, flags, files"

flags:
  animated_collection:
    paths:
      - packages/animated_collection/**
    carryforward: true
  animated_location:
    paths: 
      - packages/animated_collection/lib/src/widgets/animated_location/**
    carryforward: true

coverage:
  status:
    project:
      animated_collection: 
        flags:
          - animated_collection
      animated_location: 
        flags:
          - animated_location
