/// {@template riverpod_state_provider_annotation.value_override}
/// Stores the value to override a state provider with.
///
/// Exposed only for code generated by
/// `package:riverpod_state_provider_generator`. Not meant to be used directly
/// by user code.
/// {@endtemplate}
class ValueOverride<T> {
  /// {@macro riverpod_state_provider_annotation.value_override}
  const ValueOverride(this.value);

  /// The value to override the state provider with.
  final T value;
}
