name: imperative_page_routes
description: A Flutter library with pages from imperative routing that can be used in a declarative way.
version: 0.0.2
homepage: https://github.com/ValentinVignal/flutter_packages/tree/main/packages/imperative_page_routes
repository: https://github.com/ValentinVignal/flutter_packages
issue_tracker: https://github.com/ValentinVignal/flutter_packages/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
