name: animated_collection
description: A Flutter library with simple animated widgets and utilities methods to use with animations.
version: 0.0.1
homepage: https://github.com/ValentinVignal/flutter_packages/tree/main/packages/animated_collection
repository: https://github.com/ValentinVignal/flutter_packages
issue_tracker: https://github.com/ValentinVignal/flutter_packages/issues


environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
