name: animated_collection
description: A library of animated widgets for Flutter.
version: 0.0.0
homepage: https://github.com/ValentinVignal/flutter_packages/tree/master/animated_collection

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
