name: animated_collection
description: A Flutter library with simple animated widgets and utilities methods to use with animations.
version: 1.1.0
homepage: https://github.com/ValentinVignal/flutter_packages/tree/main/packages/animated_collection
repository: https://github.com/ValentinVignal/flutter_packages
issue_tracker: https://github.com/ValentinVignal/flutter_packages/issues


environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
