# Those are publisher names.
# cSpell:ignore subosito

name: Tests
on:
  push:
    branches:
      - main


jobs: 
  test:
    runs-on: macos-latest
    name: Tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: melos run test-coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: animated_collection
